"use client";
import {useEffect,useState} from "react";
import {AccountSession} from "../account-session";
import {AdminRecords} from "./admin-records";
type Report={id:string;target_type:string;target_id:string;title:string;reason:string;detail:string;status:string;visibility:string|null;publication?:{description:string;photo_ids:string[]}};
type Overview={counts:Record<string,number>;ai_failures:{id:string;source:string;error_code:string|null}[];audit:{action:string;target_type:string;target_id:string;created_at:string}[]};
const names:Record<string,string>={users:"Usuarios",pets:"Animales",lost_cases:"Avisos",observations:"Avistamientos",matches:"Coincidencias",moderation_reports:"Denuncias"};
function AdminPanel(){const [reports,setReports]=useState<Report[]>([]);const [overview,setOverview]=useState<Overview|null>(null);const [status,setStatus]=useState("OPEN");const [error,setError]=useState("");const [refresh,setRefresh]=useState(0);const [busy,setBusy]=useState<string|null>(null);
  useEffect(()=>{const controller=new AbortController();void Promise.all([fetch(`/api/admin/reports?status=${status}`,{cache:"no-store",signal:controller.signal}),fetch("/api/admin/overview",{cache:"no-store",signal:controller.signal})]).then(async ([reportResponse,overviewResponse])=>{if(!reportResponse.ok||!overviewResponse.ok)throw new Error("No pudimos consultar la administración. Revisá tu sesión y permisos.");const [data,summary]=await Promise.all([reportResponse.json(),overviewResponse.json()]);if(!controller.signal.aborted){setReports(data.items);setOverview(summary);setError("");}}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);});return()=>controller.abort();},[status,refresh]);
  async function action(id:string,value:string){setBusy(id);setError("");try{const response=await fetch(`/api/admin/reports/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:value})});if(!response.ok)throw new Error("No pudimos aplicar la acción.");setRefresh(value=>value+1);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos aplicar la acción.");}finally{setBusy(null);}}
  return <>{error&&<p className="notice notice-warning" role="alert">{error}</p>}{overview&&<dl className="review-details">{Object.entries(overview.counts).map(([name,total])=><div key={name}><dt>{names[name]||name}</dt><dd>{total}</dd></div>)}</dl>}
    <h2>Denuncias</h2><label className="field-label">Estado<select className="form-input" value={status} onChange={event=>setStatus(event.target.value)}><option value="OPEN">Pendientes</option><option value="ACTION_TAKEN">Con acción aplicada</option><option value="DISMISSED">Descartadas</option><option value="">Todas</option></select></label>
    {!reports.length&&<p>No hay denuncias en este estado.</p>}{reports.map(report=><article key={report.id} className="notification-card"><h3>{report.title}</h3><p>{report.reason} · {report.visibility==="HIDDEN"?"Publicación oculta":"Publicación visible"}</p><p>{report.detail||"Sin detalles adicionales"}</p>{report.publication&&<details><summary>Ver publicación denunciada</summary><p>{report.publication.description}</p><div className="notification-photos">{report.publication.photo_ids.map(id=><img key={id} src={`/api/admin/reports/${report.id}/photos/${id}`} alt="Foto de la publicación denunciada" loading="lazy"/>)}</div></details>}<div className="location-actions"><button className="text-button" type="button" disabled={busy===report.id} onClick={()=>void action(report.id,"HIDE")}>Ocultar publicación</button><button className="text-button" type="button" disabled={busy===report.id} onClick={()=>void action(report.id,"RESTORE")}>Restaurar publicación</button><button className="text-button" type="button" disabled={busy===report.id} onClick={()=>void action(report.id,"DISMISS")}>Descartar denuncia</button></div><details><summary>Bloquear al autor</summary><p className="field-help">Bloquea el acceso de la cuenta y oculta sus publicaciones. Las acciones quedan registradas.</p><button className="button button-secondary" type="button" disabled={busy===report.id} onClick={()=>void action(report.id,"BLOCK_AUTHOR")}>Confirmar bloqueo del autor</button></details></article>)}
    <AdminRecords/>
    <h2>Fallos de análisis</h2>{overview?.ai_failures.length? <ul>{overview.ai_failures.map(job=><li key={job.id}>{job.source}: {job.error_code||"Fallo sin código"}</li>)}</ul>:<p>No hay fallos registrados.</p>}
    <h2>Acciones recientes</h2>{overview?.audit.length?<ul>{overview.audit.map((item,index)=><li key={`${item.target_id}-${index}`}>{item.action} · {item.target_type} · {new Date(item.created_at).toLocaleString("es-UY")}</li>)}</ul>:<p>Todavía no hay acciones administrativas.</p>}
  </>;
}
export function Administration(){return <AccountSession>{user=>user.role==="ADMIN"?<AdminPanel/>:<p>Esta sección requiere permisos de administrador.</p>}</AccountSession>;}
