"use client";
import {useEffect,useState} from "react";
import type {FormEvent} from "react";
type RecordRow={id:string;name?:string;status?:string;moderation_status?:string;description?:string;species?:string;source_type?:string;display_name?:string;rating?:number;comment?:string;visibility?:string};
export function AdminRecords(){const [kind,setKind]=useState("lost_cases");const [records,setRecords]=useState<RecordRow[]>([]);const [editing,setEditing]=useState<string|null>(null);const [error,setError]=useState("");const [refresh,setRefresh]=useState(0);const [busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();void fetch(`/api/admin/records/${kind}`,{cache:"no-store",signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("No pudimos consultar los registros.");const data=await response.json();if(!controller.signal.aborted){setRecords(data.items);setError("");}}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);});return()=>controller.abort();},[kind,refresh]);
  async function correct(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);try{const response=await fetch(`/api/admin/publications/${kind==="lost_cases"?"lost_case":"observation"}/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({description:form.get("description")})});if(!response.ok)throw new Error("No pudimos corregir la publicación.");setEditing(null);setRefresh(value=>value+1);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos corregir la publicación.");}finally{setBusy(false);}}
  async function status(id:string,value:string){setBusy(true);try{const response=await fetch(`/api/admin/users/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:value})});if(!response.ok)throw new Error("No pudimos actualizar la cuenta.");setRefresh(value=>value+1);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos actualizar la cuenta.");}finally{setBusy(false);}}
  async function reviewVisibility(id:string,visibility:string){setBusy(true);setError("");try{const response=await fetch(`/api/admin/reviews/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({visibility})});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==="string"?data.detail:"No pudimos actualizar la reseña.");setRefresh(value=>value+1);window.dispatchEvent(new Event("mascomatch:reviews"));}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos actualizar la reseña.");}finally{setBusy(false);}}
  return <section className="analysis-section"><h2>Registros de la plataforma</h2><label className="field-label">Consultar<select className="form-input" value={kind} onChange={event=>{setKind(event.target.value);setRecords([]);setError("");setEditing(null);}}>{[["lost_cases","Avisos de pérdida"],["observations","Avistamientos y encontrados"],["pets","Animales"],["users","Usuarios"],["matches","Coincidencias"],["reviews","Reseñas"]].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{error&&<p role="alert" className="notice notice-warning">{error}</p>}
    {!records.length&&<p>No hay registros.</p>}{records.map(record=><article key={record.id} className="analysis-result"><h3>{record.display_name||record.name||record.source_type||"Registro"}</h3><p className="field-help">{record.status||record.moderation_status||record.species}</p>{record.description&&<p>{record.description}</p>}
      {kind==="reviews"&&<><p>{record.rating} de 5 estrellas · {record.visibility==="VISIBLE"?"Publicación habilitada":record.visibility==="WITHDRAWN"?"Retirada por el autor":"Oculta"}</p><p className="review-own-comment">{record.comment}</p>{record.visibility!=="WITHDRAWN"&&<button className="text-button" type="button" disabled={busy} onClick={()=>void reviewVisibility(record.id,record.visibility==="VISIBLE"?"HIDDEN":"VISIBLE")}>{record.visibility==="VISIBLE"?"Ocultar reseña":"Mostrar reseña"}</button>}</>}
      {["lost_cases","observations"].includes(kind)&&<button className="text-button" type="button" onClick={()=>setEditing(editing===record.id?null:record.id)}>Corregir descripción</button>}
      {kind==="users"&&<div className="location-actions">{record.status==="BLOCKED"?<button className="text-button" disabled={busy} type="button" onClick={()=>void status(record.id,"ACTIVE")}>Reactivar cuenta</button>:<details><summary>Bloquear cuenta</summary><button className="text-button" disabled={busy} type="button" onClick={()=>void status(record.id,"BLOCKED")}>Confirmar bloqueo</button></details>}</div>}
      {editing===record.id&&<form onSubmit={event=>void correct(event,record.id)}><label className="field-label">Descripción corregida<textarea name="description" className="form-input" required maxLength={4000} defaultValue={record.description}/></label><p className="field-help">La descripción anterior se conserva en la auditoría privada.</p><button className="button button-secondary" disabled={busy} type="submit">Guardar corrección</button></form>}
    </article>)}<p className="field-help">Se muestran hasta 50 registros recientes por categoría.</p></section>;
}
