"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import type {FormEvent} from "react";
import {AccountSession} from "../account-session";
import {MatchFeedback} from "../match-feedback";
import {ReportMatches} from "../report-matches";
import {EditCase} from "./edit-case";
type Pet={id:string;name:string;species:string;sex:string;primary_color:string;size:string};
type Case={id:string;pet_id:string;status:string;description:string;public_location:string|null;lost_at:string};
type Observation={id:string;description:string;source_type:string;observed_at:string};
type Dashboard={pets:Pet[];cases:Case[];observations:Observation[]};
type Candidate={match:{id:string;status:string;explanation:string[]};observation:{description:string;public_location:string|null;observed_at:string}};
const states:Record<string,string>={ACTIVE:"Sigue perdido",FOUND:"Encontrado",CLOSED:"Cerrado",CANCELLED:"Cancelado"};

function Reports({userId}:{userId:string}) {
  const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [refresh,setRefresh]=useState(0);const [busy,setBusy]=useState(false);const [editing,setEditing]=useState<Case|null>(null);const [selected,setSelected]=useState<string|null>(null);const [candidates,setCandidates]=useState<Candidate[]>([]);const [candidatesBusy,setCandidatesBusy]=useState(false);const [report,setReport]=useState<string|null>(null);
  useEffect(()=>{const controller=new AbortController();void fetch("/api/account/dashboard",{cache:"no-store",signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(response.status===401?"Tu sesión venció. Volvé a ingresar.":"No pudimos consultar tus avisos.");const result=await response.json();if(!controller.signal.aborted){setData(result);setError("");}}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);});return()=>controller.abort();},[userId,refresh]);
  useEffect(()=>{if(!selected)return;const controller=new AbortController();setCandidates([]);setCandidatesBusy(true);void fetch(`/api/matches/lost-cases/${selected}`,{cache:"no-store",signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error("No pudimos consultar las coincidencias.");const result=await response.json();if(!controller.signal.aborted)setCandidates(result.items);}).catch(cause=>{if(!controller.signal.aborted)setError(cause.message);}).finally(()=>{if(!controller.signal.aborted)setCandidatesBusy(false);});return()=>controller.abort();},[selected,refresh]);
  async function change(id:string,values:object){setBusy(true);setError("");setMessage("");try{const response=await fetch(`/api/account/lost-cases/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});if(!response.ok)throw new Error("No pudimos actualizar tu aviso.");setEditing(null);setMessage("Tu aviso quedó actualizado.");setRefresh(value=>value+1);}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos actualizar tu aviso.");}finally{setBusy(false);}}
  async function photo(event:FormEvent<HTMLFormElement>,id:string){event.preventDefault();setBusy(true);setError("");const form=event.currentTarget;const body=new FormData(form);body.set("owner_type","lost_case");body.set("owner_id",id);try{const response=await fetch("/api/account/photos/upload",{method:"POST",body});if(!response.ok)throw new Error("No pudimos guardar la foto. Usá JPEG, PNG o WebP de hasta 10 MB.");form.reset();setMessage("La foto quedó guardada y se procesará en segundo plano.");}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos guardar la foto.");}finally{setBusy(false);}}
  return <>{error&&<p role="alert" className="notice notice-warning">{error}</p>}{message&&<p role="status" className="notice">{message}</p>}{!data&&!error&&<p role="status">Cargando tus avisos…</p>}
    {data?.cases.length===0&&<p>Todavía no publicaste un aviso de pérdida. <Link href="/perdi">Publicar un aviso</Link></p>}
    {data?.cases.map(item=>{const pet=data.pets.find(pet=>pet.id===item.pet_id);return <article className="notification-card" key={item.id}><span className="lost-status">{states[item.status]||item.status}</span><h2>{pet?.name||"Mi animal"}</h2><p>{item.description||"Sin descripción adicional"}</p><p className="field-help">{item.public_location||"Zona no indicada"}</p>
      <div className="location-actions">{item.status==="ACTIVE"&&<Link className="text-button" href={`/perdidos/${item.id}`}>Ver publicación</Link>}<button className="text-button" type="button" onClick={()=>setEditing(item)}>Editar aviso</button><button className="text-button" type="button" onClick={()=>setSelected(selected===item.id?null:item.id)}>{selected===item.id?"Ocultar coincidencias":"Ver coincidencias"}</button>
      {item.status==="ACTIVE"?<><button className="text-button" type="button" disabled={busy} onClick={()=>void change(item.id,{status:"FOUND"})}>Marcar como encontrado</button><button className="text-button" type="button" disabled={busy} onClick={()=>void change(item.id,{status:"CLOSED"})}>Cerrar aviso</button></>:<button className="text-button" type="button" disabled={busy} onClick={()=>void change(item.id,{status:"ACTIVE"})}>Reabrir búsqueda</button>}</div>
      {editing?.id===item.id&&pet&&<EditCase caseId={item.id} description={item.description} lostAt={item.lost_at} pet={pet} onSaved={()=>{setEditing(null);setMessage("Tu aviso quedó actualizado.");setRefresh(value=>value+1);}} onCancel={()=>setEditing(null)}/>}
      <form onSubmit={event=>void photo(event,item.id)} className="photo-add-form"><label className="field-label">Agregar una foto<input name="file" type="file" accept="image/jpeg,image/png,image/webp" required/></label><button className="text-button" type="submit" disabled={busy}>Guardar foto</button></form>
      {selected===item.id&&<section><h3>Avistamientos compatibles</h3>{candidatesBusy?<p role="status">Consultando coincidencias…</p>:!candidates.length&&<p>No hay coincidencias vigentes por ahora.</p>}{candidates.map(candidate=><div className="analysis-result" key={candidate.match.id}><p>{candidate.observation.description}</p><p className="field-help">{candidate.observation.public_location||"Zona indicada en el reporte"}</p><ul>{candidate.match.explanation.map(reason=><li key={reason}>{reason}</li>)}</ul><MatchFeedback id={candidate.match.id} status={candidate.match.status}/></div>)}</section>}
    </article>;})}
    {!!data?.observations.length&&<section className="analysis-section"><h2>Reportes que compartiste</h2>{data.observations.map(item=><article className="analysis-result" key={item.id}><h3>{item.source_type==="FOUND_ANIMAL"?"Animal encontrado":"Avistamiento"}</h3><p>{item.description}</p><button type="button" className="text-button" onClick={()=>setReport(report===item.id?null:item.id)}>Ver posibles coincidencias</button>{report===item.id&&<ReportMatches observationId={item.id}/>}</article>)}</section>}
    <p><Link href="/notificaciones" className="text-button">Ver mis notificaciones</Link></p>
  </>;
}
export function MyReports(){return <AccountSession>{user=><Reports userId={user.id}/>}</AccountSession>;}
